-- -------------------------------------------------------------------
-- V2: BANCO DE DADOS LIMPO (Sem robôs que dão erro de conflito)
-- -------------------------------------------------------------------

-- 1. DELETAR TUDO QUE EXISTE (inclusive os gatilhos fantasmas da auth)
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user cascade;

drop table if exists public.user_purchases cascade;
drop table if exists public.products cascade;
drop table if exists public.profiles cascade;

-- 2. RECRIAR TABELA DE PRODUTOS
create table public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  cover_url text not null,
  pdf_url text not null,
  is_free boolean default false,
  price numeric default 9.90,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Produtos
alter table public.products enable row level security;
create policy "Produtos visiveis para todos" on public.products for select using (true);

-- 3. RECRIAR TABELA DE PERFIS (Agentes no front-end vão preencher as informações)
create table public.profiles (
  id uuid primary key,
  full_name text,
  is_subscriber boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Perfis
alter table public.profiles enable row level security;
create policy "Usuarios podem ver proprio perfil" on public.profiles for select using (auth.uid() = id);
create policy "Usuarios podem criar o proprio perfil" on public.profiles for insert with check (auth.uid() = id);
create policy "Usuarios podem atualizar proprio perfil" on public.profiles for update using (auth.uid() = id);

-- 4. RECRIAR TABELA DE COMPRAS INDIVIDUAIS
create table public.user_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  product_id bigint references public.products not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Compras
alter table public.user_purchases enable row level security;
create policy "Usuarios veem as proprias compras" on public.user_purchases for select using (auth.uid() = user_id);
create policy "Adicionar compra individual" on public.user_purchases for insert with check (auth.uid() = user_id);

-- -------------------------------------------------------------------
-- INSERIR O CATÁLOGO PLR
-- -------------------------------------------------------------------
insert into public.products (title, cover_url, pdf_url, is_free, price) values
('Dinos Goods', 'https://placehold.co/400x600/FF4500/FFF?text=Dinos+Goods', '#', true, 0),
('Capivara Goods', 'https://placehold.co/400x600/8B4513/FFF?text=Capivara', '#', false, 9.90),
('Divertidamente', 'https://placehold.co/400x600/4B0082/FFF?text=Emocoes', '#', false, 9.90),
('Bosque Goods', 'https://placehold.co/400x600/228B22/FFF?text=Bosque', '#', false, 9.90),
('BTS Goods', 'https://placehold.co/400x600/9400D3/FFF?text=BTS', '#', false, 9.90),
('Dorameira Goods', 'https://placehold.co/400x600/FF1493/FFF?text=Dorameira', '#', false, 9.90),
('Doces Fofos', 'https://placehold.co/400x600/FF69B4/FFF?text=Doces', '#', false, 9.90),
('Caktos Goods', 'https://placehold.co/400x600/32CD32/FFF?text=Caktos', '#', false, 9.90),
('Bobbie Goods Olimpo', 'https://placehold.co/400x600/FFD700/000?text=Bobbie+Olimpo', '#', false, 9.90),
('Uno do Olimpo', 'https://placehold.co/400x600/FF3366/FFF?text=UNO+do+Olimpo', '#', false, 9.90),
('Jogo de Memória Olimpo', 'https://placehold.co/400x600/00E5FF/000?text=Memoria+Olimpo', '#', false, 9.90),
('+80 Adesivos do Olimpo', 'https://placehold.co/400x600/8A2BE2/FFF?text=Adesivos', '#', false, 9.90);
